set(CASE "${CMAKE_CURRENT_BINARY_DIR}/dcy-invalidation")
file(REMOVE_RECURSE "${CASE}")
file(MAKE_DIRECTORY "${CASE}/repo")
file(COPY "${ROOT}/tests/fixture/auth.cpp" DESTINATION "${CASE}/repo")
set(DB "${CASE}/index.sqlite")
execute_process(COMMAND "${DCY}" index "${CASE}/repo" "${DB}"
  RESULT_VARIABLE rc OUTPUT_VARIABLE first ERROR_VARIABLE err)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "index failed: ${err}")
endif()
string(REGEX MATCH "generation ([0-9a-f]+)" ignored "${first}")
set(OLD_GENERATION "${CMAKE_MATCH_1}")
execute_process(COMMAND "${DCY}" query "${DB}" "login" 500
  RESULT_VARIABLE rc OUTPUT_VARIABLE context ERROR_VARIABLE err)
string(REGEX MATCH "function login \\[ref=E([0-9]+)\\]" ignored "${context}")
set(OLD_ENTITY "${CMAKE_MATCH_1}")
if(NOT rc EQUAL 0 OR OLD_ENTITY STREQUAL "")
  message(FATAL_ERROR "query failed: ${context} ${err}")
endif()
execute_process(COMMAND "${DCY}" goal "${DB}" "login"
  RESULT_VARIABLE rc OUTPUT_VARIABLE goal ERROR_VARIABLE err)
string(REGEX MATCH "G([0-9]+)" ignored "${goal}")
set(GOAL "${CMAKE_MATCH_1}")
execute_process(COMMAND "${DCY}" record "${DB}" "${GOAL}" fact "login had old behavior" "${OLD_ENTITY}"
  RESULT_VARIABLE rc OUTPUT_VARIABLE record ERROR_VARIABLE err)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "record failed: ${err}")
endif()
file(APPEND "${CASE}/repo/auth.cpp" "\nint changed_function() { return 1; }\n")
execute_process(COMMAND "${DCY}" index "${CASE}/repo" "${DB}"
  RESULT_VARIABLE rc OUTPUT_VARIABLE second ERROR_VARIABLE err)
if(NOT rc EQUAL 0 OR NOT second MATCHES "changed 1")
  message(FATAL_ERROR "reindex failed: ${second} ${err}")
endif()
execute_process(COMMAND "${DCY}" context "${DB}" "${GOAL}" 500
  RESULT_VARIABLE rc ERROR_VARIABLE err)
if(rc EQUAL 0 OR NOT err MATCHES "stale generation")
  message(FATAL_ERROR "stale goal was accepted: ${rc} ${err}")
endif()
execute_process(COMMAND "${DCY}" source "${DB}" "${OLD_ENTITY}" "${OLD_GENERATION}" 1000
  RESULT_VARIABLE rc ERROR_VARIABLE err)
if(rc EQUAL 0 OR NOT err MATCHES "stale generation")
  message(FATAL_ERROR "stale source was accepted: ${rc} ${err}")
endif()
file(REMOVE "${CASE}/repo/auth.cpp")
execute_process(COMMAND "${DCY}" index "${CASE}/repo" "${DB}"
  RESULT_VARIABLE rc OUTPUT_VARIABLE third ERROR_VARIABLE err)
if(NOT rc EQUAL 0 OR NOT third MATCHES "removed 1")
  message(FATAL_ERROR "deletion invalidation failed: ${third} ${err}")
endif()
