set(DB "${CMAKE_CURRENT_BINARY_DIR}/dcy-smoke.sqlite")
file(REMOVE "${DB}" "${DB}-wal" "${DB}-shm")
execute_process(COMMAND "${DCY}" index "${ROOT}/tests/fixture" "${DB}"
  RESULT_VARIABLE rc OUTPUT_VARIABLE first ERROR_VARIABLE err)
if(NOT rc EQUAL 0 OR NOT first MATCHES "changed 1")
  message(FATAL_ERROR "initial index failed: ${rc} ${first} ${err}")
endif()
string(REGEX MATCH "generation ([0-9a-f]+)" ignored "${first}")
set(GENERATION "${CMAKE_MATCH_1}")
execute_process(COMMAND "${DCY}" index "${ROOT}/tests/fixture" "${DB}"
  RESULT_VARIABLE rc OUTPUT_VARIABLE second ERROR_VARIABLE err)
if(NOT rc EQUAL 0 OR NOT second MATCHES "unchanged 1" OR NOT second MATCHES "changed 0")
  message(FATAL_ERROR "incremental index failed: ${rc} ${second} ${err}")
endif()
execute_process(COMMAND "${DCY}" query "${DB}" "login" 500
  RESULT_VARIABLE rc OUTPUT_VARIABLE context ERROR_VARIABLE err)
if(NOT rc EQUAL 0 OR NOT context MATCHES "login" OR NOT context MATCHES "subscription_active")
  message(FATAL_ERROR "retrieval failed: ${rc} ${context} ${err}")
endif()
execute_process(COMMAND "${DCY}" query-fts "${DB}" "login" 500
  RESULT_VARIABLE rc OUTPUT_VARIABLE lexical ERROR_VARIABLE err)
if(NOT rc EQUAL 0 OR NOT lexical MATCHES "login" OR lexical MATCHES "subscription_active")
  message(FATAL_ERROR "FTS ablation failed: ${rc} ${lexical} ${err}")
endif()
execute_process(COMMAND "${DCY}" query "${DB}" "403" 500
  RESULT_VARIABLE rc OUTPUT_VARIABLE by_body ERROR_VARIABLE err)
if(NOT rc EQUAL 0 OR NOT by_body MATCHES "login")
  message(FATAL_ERROR "source-text search failed: ${rc} ${by_body} ${err}")
endif()
string(LENGTH "${context}" context_bytes)
if(context_bytes GREATER 500)
  message(FATAL_ERROR "ORMT budget exceeded: ${context_bytes}")
endif()
execute_process(COMMAND "${DCY}" query "${DB}" "login" 200
  RESULT_VARIABLE rc OUTPUT_VARIABLE compact ERROR_VARIABLE err)
if(NOT rc EQUAL 0 OR NOT compact MATCHES "login @auth.cpp:[0-9]+-[0-9]+ \\[ref=E[0-9]+\\]")
  message(FATAL_ERROR "ORMT compact fallback failed: ${compact} ${err}")
endif()
execute_process(COMMAND "${DCY}" query "${DB}" "login" 130
  RESULT_VARIABLE rc OUTPUT_VARIABLE minimal ERROR_VARIABLE err)
if(NOT rc EQUAL 0 OR NOT minimal MATCHES "login \\[ref=E[0-9]+\\]" OR minimal MATCHES "@auth.cpp")
  message(FATAL_ERROR "ORMT minimal fallback failed: ${minimal} ${err}")
endif()
# Entity IDs are routing metadata and must never lead a rendered line, at any level.
foreach(probe 500 200 130)
  execute_process(COMMAND "${DCY}" query "${DB}" "login" "${probe}"
    RESULT_VARIABLE rc OUTPUT_VARIABLE rendered ERROR_VARIABLE err)
  if(NOT rc EQUAL 0 OR rendered MATCHES "\n *E[0-9]+ ")
    message(FATAL_ERROR "entity ID leads a line at budget ${probe}: ${rendered} ${err}")
  endif()
endforeach()
execute_process(COMMAND "${DCY}" query "${DB}" "login" 80
  RESULT_VARIABLE rc ERROR_VARIABLE err)
if(rc EQUAL 0 OR NOT err MATCHES "budget too small")
  message(FATAL_ERROR "ORMT accepted impossible budget: ${rc} ${err}")
endif()
string(REGEX MATCH "function login \\[ref=E([0-9]+)\\]" ignored "${context}")
set(ENTITY "${CMAKE_MATCH_1}")
if(ENTITY STREQUAL "")
  message(FATAL_ERROR "login entity missing: ${context}")
endif()
execute_process(COMMAND "${DCY}" source "${DB}" "${ENTITY}" "${GENERATION}" 1000
  RESULT_VARIABLE rc OUTPUT_VARIABLE source ERROR_VARIABLE err)
if(NOT rc EQUAL 0 OR NOT source MATCHES "return 403")
  message(FATAL_ERROR "exact source failed: ${rc} ${source} ${err}")
endif()
execute_process(COMMAND "${DCY}" goal "${DB}" "fix login 403"
  RESULT_VARIABLE rc OUTPUT_VARIABLE goal ERROR_VARIABLE err)
if(NOT rc EQUAL 0 OR NOT goal MATCHES "G([0-9]+)")
  message(FATAL_ERROR "goal failed: ${rc} ${goal} ${err}")
endif()
string(REGEX MATCH "G([0-9]+)" ignored "${goal}")
set(GOAL "${CMAKE_MATCH_1}")
execute_process(COMMAND "${DCY}" record "${DB}" "${GOAL}" fact "login returns 403" "${ENTITY}"
  RESULT_VARIABLE rc OUTPUT_VARIABLE record ERROR_VARIABLE err)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "record failed: ${rc} ${record} ${err}")
endif()
execute_process(COMMAND "${DCY}" context "${DB}" "${GOAL}" 500
  RESULT_VARIABLE rc OUTPUT_VARIABLE resumed ERROR_VARIABLE err)
if(NOT rc EQUAL 0 OR NOT resumed MATCHES "STATE fact")
  message(FATAL_ERROR "external state failed: ${rc} ${resumed} ${err}")
endif()
execute_process(COMMAND "${DCY}" finish "${DB}" "${GOAL}" resolved
  RESULT_VARIABLE rc OUTPUT_VARIABLE finished ERROR_VARIABLE err)
if(NOT rc EQUAL 0 OR NOT finished MATCHES "resolved")
  message(FATAL_ERROR "goal completion failed: ${rc} ${finished} ${err}")
endif()
execute_process(COMMAND "${DCY}" context "${DB}" "${GOAL}" 500
  RESULT_VARIABLE rc ERROR_VARIABLE err)
if(rc EQUAL 0 OR NOT err MATCHES "not active")
  message(FATAL_ERROR "finished goal was resumed: ${rc} ${err}")
endif()
